# Generated by Django 4.2.26 on 2025-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_tag',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('bestseller', 'Bestseller'), ('spicy', 'Spicy'), ('discount', 'Discount'), ('limited', 'Limited')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
