# Generated by Django 4.2.26 on 2025-12-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_product_offer_tag_product_offer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_homepage_offer',
            field=models.BooleanField(default=False, verbose_name='Show in Homepage Offer Section'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_discount_percentage',
            field=models.IntegerField(default=0, help_text='Percentage discount e.g. 20'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_title',
            field=models.CharField(blank=True, help_text='e.g. Tasty Thursdays', max_length=100, null=True),
        ),
    ]
